# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e159b53cf8640a1c6654979ebf5eefba1c5028780f6a4814ebf0ebc80e68dfd943029d0bc68ab24a74b2f96eaee39e119ebbd7a1f6eddb62477e31cdc3dec6e4

test:
  secret_key_base: 7cb304b8654606458af4759ec16cea53c0dc0c555adec5f0adb9dda544b6edd30bf2c0f658dc65fae79808189b74aec6ff620c51626ab3f4287e65ee71911fb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
